# Imports

In [1]:
import pandas as pd
import numpy as np
import glob
import os

In [14]:
!ls datasets.uwf.edu/data/UWF-ZeekDataSum25-1/parquet/2025-05-18\ -\ 2025-05-25/part-00000-e1c83503-04fd-4fe4-bd2d-faeaad297203-c000.snappy.parquet

'datasets.uwf.edu/data/UWF-ZeekDataSum25-1/parquet/2025-05-18 - 2025-05-25/part-00000-e1c83503-04fd-4fe4-bd2d-faeaad297203-c000.snappy.parquet'

In [2]:
root_path = 'datasets.uwf.edu/data/UWF-ZeekDataSum25-1/csv/'

benign = pd.read_csv(f"{root_path}/Benign/part-00000-2ac3ee1a-f94a-44bb-9413-dbfa36b751da-c000.csv")
defense_evasion = pd.read_csv(f"{root_path}/Defense_Evasion/part-00000-85b1a966-f6cf-481a-b60d-fd80ec61a72b-c000.csv")
discovery = pd.read_csv(f"{root_path}/Discovery/part-00000-20202de3-67ac-4628-90e5-6f7a8153737d-c000.csv")
initial_access = pd.read_csv(f"{root_path}/Initial_Access/part-00000-cdf1eaba-5033-45e8-94f5-c846fe812699-c000.csv")
lateral_movement = pd.read_csv(f"{root_path}/Lateral_Movement/part-00000-4890c258-40e8-4ef8-b345-06d436539b95-c000.csv")
privilege_escalation = pd.read_csv(f"{root_path}/Privilege_Escalation/part-00000-b16554a3-7c9d-4ef8-b8d1-2b557946dd0f-c000.csv")
reconnaissance = pd.read_csv(f"{root_path}/Reconnaissance/part-00000-27b9c76f-8291-49ef-bd5a-c47c18444b18-c000.csv")

In [3]:
benign.head()

,community_id,conn_state,duration,history,src_ip_zeek,src_port_zeek,dest_ip_zeek,dest_port_zeek,local_orig,local_resp,...,resp_ip_bytes,resp_pkts,service,ts,uid,datetime,label_tactic,label_technique,label_binary,label_cve
0,1:Lg+cZhvfxmP9GJkedFhQoyGiglw=,S0,NaN,D,143.88.0.6,40511,199.7.83.42,53,False,False,...,0,0,dns,1.749193e+09,CisbUC33gtqDbJqMcc,2025-06-06T06:51:17.122Z,none,none,False,none
1,1:GT76GXYVgIg4twXTOLUOwL47oQw=,S0,0.000008,D,143.88.4.12,55378,1.1.1.1,53,False,False,...,0,0,dns,1.749191e+09,Cic9qfKsbGDkwoJ79,2025-06-06T06:16:25.058Z,none,none,False,none
2,1:Q/BJ2dwdsUCSilbXgf89H+P5xWI=,S0,0.000015,D,143.88.0.22,46217,143.88.255.10,53,False,False,...,0,0,dns,1.749192e+09,C53NvV3okkT7PqjZXa,2025-06-06T06:44:28.592Z,none,none,False,none
3,1:AKkZZ4+ijVLUtMeO9TOsu6faLAw=,S0,7.035917,D,143.88.0.2,31957,143.88.255.10,53,False,False,...,0,0,dns,1.749193e+09,CdZVxu2H4ytHGVlUrd,2025-06-06T06:56:34.108Z,none,none,False,none
4,1:BkCKUhxawfmwIn3xDcsS9r2q4wY=,S0,0.000018,D,143.88.0.14,14637,1.1.1.1,53,False,False,...,0,0,dns,1.749193e+09,CNNpof2vxxL95QSAEf,2025-06-06T06:50:42.067Z,none,none,False,none

In [4]:
benign.info()

<class 'pandas.DataFrame'>
RangeIndex: 28964 entries, 0 to 28963
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   community_id     28964 non-null  str
 1   conn_state       28964 non-null  str
 2   duration         25046 non-null  float64
 3   history          28919 non-null  str
 4   src_ip_zeek      28964 non-null  str
 5   src_port_zeek    28964 non-null  int64
 6   dest_ip_zeek     28964 non-null  str
 7   dest_port_zeek   28964 non-null  int64
 8   local_orig       28964 non-null  bool
 9   local_resp       28964 non-null  bool
 10  missed_bytes     28964 non-null  int64
 11  orig_bytes       25046 non-null  float64
 12  orig_ip_bytes    28964 non-null  int64
 13  orig_pkts        28964 non-null  int64
 14  proto            28964 non-null  str
 15  resp_bytes       25046 non-null  float64
 16  resp_ip_bytes    28964 non-null  int64
 17  resp_pkts        28964 non-null  int64
 18  service          28738 non-null  str
 19  ts               28964 non-null  float64
 20  uid              28964 non-null  str
 21  datetime         28964 non-null  str
 22  label_tactic     28964 non-null  str
 23  label_technique  28964 non-null  str
 24  label_binary     28964 non-null  bool
 25  label_cve        28964 non-null  str
dtypes: bool(3), float64(4), int64(7), str(12)
memory usage: 8.3 MB

In [5]:
benign.columns

Index(['community_id', 'conn_state', 'duration', 'history', 'src_ip_zeek',
       'src_port_zeek', 'dest_ip_zeek', 'dest_port_zeek', 'local_orig',
       'local_resp', 'missed_bytes', 'orig_bytes', 'orig_ip_bytes',
       'orig_pkts', 'proto', 'resp_bytes', 'resp_ip_bytes', 'resp_pkts',
       'service', 'ts', 'uid', 'datetime', 'label_tactic', 'label_technique',
       'label_binary', 'label_cve'],
      dtype='str')

In [6]:
benign.describe()

,duration,src_port_zeek,dest_port_zeek,missed_bytes,orig_bytes,orig_ip_bytes,orig_pkts,resp_bytes,resp_ip_bytes,resp_pkts,ts
count,2.504600e+04,28964.000000,28964.000000,28964.0,25046.000000,28964.000000,28964.000000,25046.000000,28964.000000,28964.000000,2.896400e+04
mean,5.785377e-01,40252.915757,60.752348,0.0,102.839815,152.066600,2.059350,0.515172,0.487053,0.001485,1.748800e+09
std,2.425523e+00,16227.229481,192.046297,0.0,95.332120,123.043057,1.289995,12.424025,12.632493,0.038503,4.161064e+05
min,9.536743e-07,3.000000,1.000000,0.0,62.000000,56.000000,1.000000,0.000000,0.000000,0.000000,1.747958e+09
25%,9.059906e-06,33118.500000,53.000000,0.0,76.000000,132.000000,2.000000,0.000000,0.000000,0.000000,1.748467e+09
50%,1.406670e-05,43114.000000,53.000000,0.0,76.000000,132.000000,2.000000,0.000000,0.000000,0.000000,1.748870e+09
75%,1.788139e-05,52919.250000,53.000000,0.0,106.000000,162.000000,2.000000,0.000000,0.000000,0.000000,1.749148e+09
max,8.491066e+01,65531.000000,5355.000000,0.0,2912.000000,4368.000000,52.000000,311.000000,339.000000,1.000000,1.749427e+09

In [9]:
df = pd.read_parquet("part-00000-e1c83503-04fd-4fe4-bd2d-faeaad297203-c000.snappy.parquet", engine='pyarrow')

In [10]:
df.head()

,community_id,conn_state,duration,history,src_ip_zeek,src_port_zeek,dest_ip_zeek,dest_port_zeek,local_orig,local_resp,...,resp_ip_bytes,resp_pkts,service,ts,uid,datetime,label_tactic,label_technique,label_binary,label_cve
0,1:HRhL9iKr3apk62PYSnevxANSt18=,S0,0.000014,D,143.88.0.14,40651,143.88.255.10,53,False,False,...,0,0,dns,1.748067e+09,C7JseOWeUhYqNdGFe,2025-05-24 06:06:45.324890,none,none,False,none
1,1:WwjkCAq/BnmCAbQ44dBNYWAfhow=,S0,0.000014,D,143.88.4.11,37581,143.88.255.10,53,False,False,...,0,0,dns,1.748070e+09,CSDrLF2Vc4Fn3JxWxe,2025-05-24 06:53:34.517867,none,none,False,none
2,1:NZlD3bCbZD0WDgarGknxqPVM904=,S0,NaN,D,143.88.0.18,9797,192.5.5.241,53,False,False,...,0,0,dns,1.748073e+09,CkOrWusKaadPgnFyd,2025-05-24 07:55:37.079694,none,none,False,none
3,1:E4v/0MCGMsj9T8bJoB1ztzjlF8w=,S0,0.000011,D,143.88.0.10,13752,143.88.255.10,53,False,False,...,0,0,dns,1.748069e+09,CGms2p3WJVEAzXzMjd,2025-05-24 06:42:10.439794,none,none,False,none
4,1:s/S5zp8W9/VG2TTxLkM05ybeKic=,S0,0.000014,D,143.88.0.18,37780,143.88.255.10,53,False,False,...,0,0,dns,1.748069e+09,CGVPFr4oVUpO1eTX3f,2025-05-24 06:41:25.822938,none,none,False,none

In [11]:
df.describe()

,duration,src_port_zeek,dest_port_zeek,missed_bytes,orig_bytes,orig_ip_bytes,orig_pkts,resp_bytes,resp_ip_bytes,resp_pkts,ts,datetime
count,40676.000000,49893.000000,49893.000000,49893.000000,40676.000000,49893.000000,49893.000000,4.067600e+04,4.989300e+04,49893.000000,4.989300e+04,49893
mean,0.849661,40248.492835,63.690518,3.147135,112.333661,157.917103,2.101517,4.042620e+01,3.422236e+01,0.025134,1.748045e+09,2025-05-24 00:01:05.038027008
min,0.000002,3.000000,1.000000,0.000000,62.000000,56.000000,1.000000,0.000000e+00,0.000000e+00,0.000000,1.747958e+09,2025-05-23 00:00:00.895212
25%,0.000013,33115.000000,53.000000,0.000000,76.000000,132.000000,2.000000,0.000000e+00,0.000000e+00,0.000000,1.748002e+09,2025-05-23 11:59:02.655431936
50%,0.000015,43243.000000,53.000000,0.000000,106.000000,132.000000,2.000000,0.000000e+00,0.000000e+00,0.000000,1.748045e+09,2025-05-24 00:03:26.919877120
75%,0.000017,53179.000000,53.000000,0.000000,106.000000,162.000000,2.000000,0.000000e+00,0.000000e+00,0.000000,1.748088e+09,2025-05-24 11:55:39.479607040
max,171.023821,65532.000000,5355.000000,157020.000000,4090.000000,10702.000000,127.000000,1.617629e+06,1.678217e+06,1165.000000,1.748131e+09,2025-05-24 23:59:56.272250
std,2.859074,16489.565410,226.359965,702.967366,120.118852,158.362884,1.709447,8.020665e+03,7.513270e+03,5.215808,4.985820e+04,NaN

In [12]:
df.columns

Index(['community_id', 'conn_state', 'duration', 'history', 'src_ip_zeek',
       'src_port_zeek', 'dest_ip_zeek', 'dest_port_zeek', 'local_orig',
       'local_resp', 'missed_bytes', 'orig_bytes', 'orig_ip_bytes',
       'orig_pkts', 'proto', 'resp_bytes', 'resp_ip_bytes', 'resp_pkts',
       'service', 'ts', 'uid', 'datetime', 'label_tactic', 'label_technique',
       'label_binary', 'label_cve'],
      dtype='str')

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49893 entries, 0 to 49892
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   community_id     49893 non-null  str
 1   conn_state       49893 non-null  str
 2   duration         40676 non-null  float64
 3   history          49755 non-null  str
 4   src_ip_zeek      49893 non-null  str
 5   src_port_zeek    49893 non-null  int64
 6   dest_ip_zeek     49893 non-null  str
 7   dest_port_zeek   49893 non-null  int64
 8   local_orig       49893 non-null  bool
 9   local_resp       49893 non-null  bool
 10  missed_bytes     49893 non-null  int64
 11  orig_bytes       40676 non-null  float64
 12  orig_ip_bytes    49893 non-null  int64
 13  orig_pkts        49893 non-null  int64
 14  proto            49893 non-null  str
 15  resp_bytes       40676 non-null  float64
 16  resp_ip_bytes    49893 non-null  int64
 17  resp_pkts        49893 non-null  int64
 18  service          49343 non-null  str
 19  ts               49893 non-null  float64
 20  uid              49893 non-null  str
 21  datetime         49893 non-null  datetime64[ns]
 22  label_tactic     49893 non-null  str
 23  label_technique  49893 non-null  str
 24  label_binary     49893 non-null  str
 25  label_cve        49893 non-null  str
dtypes: bool(2), datetime64[ns](1), float64(4), int64(7), str(12)
memory usage: 13.9 MB

In [18]:
df['label_binary'].unique()

<ArrowStringArray>
['False']
Length: 1, dtype: str